server:
  port: 8082

#jdbc
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis
    max-wait: -1
    max-idle: 8
    min-idle: 0
    max-active: 10
    timeout: 30000

  application:
    name: order
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myorder

    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#mybatis
mybatis:
  type-aliases-package: com.bdqn.order.pojo

  mapperLocations: classpath*:mybatis/**/*Mapper.xml


